/*
-- Project Title: UK Online Retail Business Performance and Revenue Optimization Analysis Using SQL
-- Dataset Source: UCI Machine Learning Repository – Online Retail Dataset
-- Industry: Retail / E-Commerce
-- Dataset: https://archive.ics.uci.edu/dataset/352/online+retail
-- Business Problem: The company operates a global online retail business and generates revenue through the sale of thousands of products across multiple countries.
-- Management lacks visibility into:
-- 1. Which products drive the majority of revenue
-- 2. Which customers generate the highest business value
-- 3. Which markets offer the greatest growth opportunities
-- 4. Which products underperform or generate operational inefficiencies
-- 5. How purchasing behavior influences overall business performance

-- Without these insights, the company cannot effectively optimize inventory, marketing spend, customer targeting, or expansion strategies.

-- Project Objective: To analyze transactional retail data and identify the key revenue drivers, customer value segments, product performance patterns, and geographic opportunities that can support revenue growth and business optimization.

-- End Consumer / Stakeholder Perspective

-- Chief Executive Officer (CEO)

-- Needs:
Revenue growth opportunities
Market expansion opportunities
Business performance overview

-- Sales Director

-- Needs:
Top revenue products
Top customers
Sales trends

-- Marketing Director

-- Needs:
High-value customer segments
Customer purchasing patterns
Customer targeting opportunities

-- Operations Director

-- Needs:
Product demand insights
Inventory planning insights
Product return analysis
Final Analytical Perspective
Revenue Optimization and Business Growth

-- Aim to find: What products, customers, and markets drive business performance, 
                and how can the company optimize them to maximize revenue growth?
  
-- Tools used:
- SQL Server Management Studio (SSMS)
- SQL

Key Analysis Performed:
-- 10 KPIs
   10 Easy problems
   10 Medium problems
   10 Difficult problems
   10 Univariate problems
   10 Bivariate problems
   10 Multivariate problems
   10 CTE related problems
   10 Window functions related problems
   10 Customer Value Analysis / RFM related problems
  */
  
  -- =====================================================
-- DATA QUALITY ANALYSIS
-- =====================================================

-- 1. Missing Customer IDs
-- =====================================================
-- Columns used: CustomerID
SELECT COUNT(*) AS missing_customer_ids
FROM dbo.online_retail_clean
WHERE CustomerID IS NULL;
-- =====================================================

-- =====================================================
-- 2. Missing Product Descriptions
-- =====================================================
-- Columns used: Description
SELECT COUNT(*) AS missing_descriptions
FROM dbo.online_retail_clean
WHERE Description IS NULL;
-- =====================================================

-- =====================================================
-- 3. Negative Quantity Transactions
-- =====================================================
-- Columns used: Quantity
SELECT COUNT(*) AS negative_quantity_transactions
FROM dbo.online_retail_clean
WHERE Quantity < 0;
-- =====================================================

-- =====================================================
-- 4. Zero or Negative Unit Prices
-- =====================================================
-- Columns used: UnitPrice
SELECT COUNT(*) AS zero_or_negative_prices
FROM dbo.online_retail_clean
WHERE UnitPrice <= 0;
-- =====================================================

-- =====================================================
-- 5. Cancelled Orders
-- =====================================================
-- Columns used: InvoiceNo
SELECT COUNT(DISTINCT InvoiceNo) AS cancelled_orders
FROM dbo.online_retail_clean
WHERE InvoiceNo LIKE 'C%';
-- =====================================================

  
-- =====================================================
-- KPI ANALYSIS
-- =====================================================

-- =====================================================
-- 1. Total revenue generated by the business
-- =====================================================
-- Columns used: Quantity, UnitPrice
-- Query:
SELECT
    ROUND(SUM(Quantity * UnitPrice), 2) AS total_revenue
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0;
-- =====================================================

-- =====================================================
-- 2. Total number of orders processed
-- =====================================================
-- Columns used: InvoiceNo, Quantity
-- Query:
SELECT
    COUNT(DISTINCT InvoiceNo) AS total_orders
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0;
-- =====================================================

-- =====================================================
-- 3. Total number of customers served
-- =====================================================
-- Columns used: CustomerID, Quantity
-- Query:
SELECT
    COUNT(DISTINCT CustomerID) AS total_customers
FROM dbo.online_retail_clean
WHERE CustomerID IS NOT NULL
  AND Quantity > 0;
-- =====================================================

-- =====================================================
-- 4. Average order value generated
-- =====================================================
-- Columns used: InvoiceNo, Quantity, UnitPrice
-- Query:
SELECT
    ROUND(
        SUM(Quantity * UnitPrice) / COUNT(DISTINCT InvoiceNo),
        2
    ) AS average_order_value
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0;
-- =====================================================

-- =====================================================
-- 5. Average customer value generated
-- =====================================================
-- Columns used: CustomerID, Quantity, UnitPrice
-- Query:
SELECT
    ROUND(
        SUM(Quantity * UnitPrice) / COUNT(DISTINCT CustomerID),
        2
    ) AS average_customer_value
FROM dbo.online_retail_clean
WHERE CustomerID IS NOT NULL
  AND Quantity > 0
  AND UnitPrice > 0;
-- =====================================================

-- =====================================================
-- 6. Total quantity of products sold
-- =====================================================
-- Columns used: Quantity
-- Query:
SELECT
    SUM(Quantity) AS total_quantity_sold
FROM dbo.online_retail_clean
WHERE Quantity > 0;
-- =====================================================

-- =====================================================
-- 7. Total number of products sold
-- =====================================================
-- Columns used: StockCode, Quantity
-- Query:
SELECT
    COUNT(DISTINCT StockCode) AS total_unique_products_sold
FROM dbo.online_retail_clean
WHERE Quantity > 0;
-- =====================================================

-- =====================================================
-- 8. Revenue lost through product returns
-- =====================================================
-- Columns used: Quantity, UnitPrice
-- Query:
SELECT
    ROUND(SUM(ABS(Quantity) * UnitPrice), 2) AS revenue_lost_through_returns
FROM dbo.online_retail_clean
WHERE Quantity < 0
  AND UnitPrice > 0;
-- =====================================================

-- =====================================================
-- 9. Percentage of unidentified customers
-- =====================================================
-- Columns used: CustomerID
-- Query:
SELECT
    ROUND(
        SUM(CASE WHEN CustomerID IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS unidentified_customer_percentage
FROM dbo.online_retail_clean;
-- =====================================================

-- =====================================================
-- 10. Average revenue generated per transaction
-- =====================================================
-- Columns used: Quantity, UnitPrice
-- Query:
SELECT
    ROUND(AVG(Quantity * UnitPrice), 2) AS average_revenue_per_transaction
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0;
-- =====================================================

-- EASY SQL PROBLEMS
-- =====================================================

-- =====================================================
-- 1. Total transactions recorded
-- =====================================================
-- Columns used: InvoiceNo
-- Query:
SELECT
    COUNT(*) AS total_transactions
FROM dbo.online_retail_clean;
-- =====================================================

-- =====================================================
-- 2. Total countries served
-- =====================================================
-- Columns used: Country
-- Query:
SELECT
    COUNT(DISTINCT Country) AS total_countries
FROM dbo.online_retail_clean;
-- =====================================================

-- =====================================================
-- 3. Total products available
-- =====================================================
-- Columns used: StockCode
-- Query:
SELECT
    COUNT(DISTINCT StockCode) AS total_products_available
FROM dbo.online_retail_clean;
-- =====================================================

-- =====================================================
-- 4. Total identified customers
-- =====================================================
-- Columns used: CustomerID
-- Query:
SELECT
    COUNT(DISTINCT CustomerID) AS total_identified_customers
FROM dbo.online_retail_clean
WHERE CustomerID IS NOT NULL;
-- =====================================================

-- =====================================================
-- 5. Earliest transaction recorded
-- =====================================================
-- Columns used: InvoiceDate
-- Query:
SELECT
    MIN(InvoiceDate) AS earliest_transaction_date
FROM dbo.online_retail_clean;
-- =====================================================

-- =====================================================
-- 6. Latest transaction recorded
-- =====================================================
-- Columns used: InvoiceDate
-- Query:
SELECT
    MAX(InvoiceDate) AS latest_transaction_date
FROM dbo.online_retail_clean;
-- =====================================================

-- =====================================================
-- 7. Highest product price recorded
-- =====================================================
-- Columns used: UnitPrice
-- Query:
SELECT
    MAX(UnitPrice) AS highest_product_price
FROM dbo.online_retail_clean;
-- =====================================================

-- =====================================================
-- 8. Lowest product price recorded
-- =====================================================
-- Columns used: UnitPrice
-- Query:
SELECT
    MIN(UnitPrice) AS lowest_product_price
FROM dbo.online_retail_clean
WHERE UnitPrice > 0;
-- =====================================================

-- =====================================================
-- 9. Largest quantity sold in a single transaction
-- =====================================================
-- Columns used: Quantity
-- Query:
SELECT
    MAX(Quantity) AS largest_quantity_sold
FROM dbo.online_retail_clean;
-- =====================================================

-- =====================================================
-- 10. Total transactions originating from the United Kingdom
-- =====================================================
-- Columns used: Country
-- Query:
SELECT
    COUNT(*) AS uk_transactions
FROM dbo.online_retail_clean
WHERE Country = 'United Kingdom';
-- =====================================================

-- MEDIUM SQL PROBLEMS
-- =====================================================

-- =====================================================
-- 1. Top 10 revenue-generating products
-- =====================================================
-- Columns used: Description, Quantity, UnitPrice
-- Query:
SELECT TOP 10
    Description,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0
  AND Description IS NOT NULL
GROUP BY Description
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 2. Top 10 products by sales volume
-- =====================================================
-- Columns used: Description, Quantity
-- Query:
SELECT TOP 10
    Description,
    SUM(Quantity) AS total_quantity_sold
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND Description IS NOT NULL
GROUP BY Description
ORDER BY total_quantity_sold DESC;
-- =====================================================

-- =====================================================
-- 3. Top 10 revenue-generating customers
-- =====================================================
-- Columns used: CustomerID, Quantity, UnitPrice
-- Query:
SELECT TOP 10
    CustomerID,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue
FROM dbo.online_retail_clean
WHERE CustomerID IS NOT NULL
  AND Quantity > 0
  AND UnitPrice > 0
GROUP BY CustomerID
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 4. Top 10 revenue-generating countries
-- =====================================================
-- Columns used: Country, Quantity, UnitPrice
-- Query:
SELECT TOP 10
    Country,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0
GROUP BY Country
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 5. Monthly revenue trends
-- =====================================================
-- Columns used: InvoiceDate, Quantity, UnitPrice
-- Query:
SELECT
    YEAR(InvoiceDate) AS sales_year,
    MONTH(InvoiceDate) AS sales_month,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0
GROUP BY YEAR(InvoiceDate), MONTH(InvoiceDate)
ORDER BY sales_year, sales_month;
-- =====================================================

-- =====================================================
-- 6. Monthly order trends
-- =====================================================
-- Columns used: InvoiceDate, InvoiceNo, Quantity
-- Query:
SELECT
    YEAR(InvoiceDate) AS sales_year,
    MONTH(InvoiceDate) AS sales_month,
    COUNT(DISTINCT InvoiceNo) AS total_orders
FROM dbo.online_retail_clean
WHERE Quantity > 0
GROUP BY YEAR(InvoiceDate), MONTH(InvoiceDate)
ORDER BY sales_year, sales_month;
-- =====================================================

-- =====================================================
-- 7. Average order value by country
-- =====================================================
-- Columns used: Country, InvoiceNo, Quantity, UnitPrice
-- Query:
SELECT
    Country,
    ROUND(
        SUM(Quantity * UnitPrice) / COUNT(DISTINCT InvoiceNo),
        2
    ) AS average_order_value
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0
GROUP BY Country
ORDER BY average_order_value DESC;
-- =====================================================

-- =====================================================
-- 8. Products generating more than £50,000 revenue
-- =====================================================
-- Columns used: Description, Quantity, UnitPrice
-- Query:
SELECT
    Description,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0
  AND Description IS NOT NULL
GROUP BY Description
HAVING SUM(Quantity * UnitPrice) > 50000
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 9. Customers placing more than 20 orders
-- =====================================================
-- Columns used: CustomerID, InvoiceNo, Quantity
-- Query:
SELECT
    CustomerID,
    COUNT(DISTINCT InvoiceNo) AS total_orders
FROM dbo.online_retail_clean
WHERE CustomerID IS NOT NULL
  AND Quantity > 0
GROUP BY CustomerID
HAVING COUNT(DISTINCT InvoiceNo) > 20
ORDER BY total_orders DESC;
-- =====================================================

-- =====================================================
-- 10. Most frequently purchased products
-- =====================================================
-- Columns used: Description, InvoiceNo, Quantity
-- Query:
SELECT TOP 10
    Description,
    COUNT(*) AS purchase_frequency
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND Description IS NOT NULL
GROUP BY Description
ORDER BY purchase_frequency DESC;
-- =====================================================

-- DIFFICULT SQL PROBLEMS
-- =====================================================

-- =====================================================
-- 1. Highest revenue-generating product within each country
-- =====================================================
-- Columns used: Country, Description, Quantity, UnitPrice
-- Query:
WITH ProductCountryRevenue AS (
    SELECT
        Country,
        Description,
        ROUND(SUM(Quantity * UnitPrice), 2) AS revenue,
        ROW_NUMBER() OVER (
            PARTITION BY Country
            ORDER BY SUM(Quantity * UnitPrice) DESC
        ) AS rn
    FROM dbo.online_retail_clean
    WHERE Quantity > 0
      AND UnitPrice > 0
      AND Description IS NOT NULL
    GROUP BY Country, Description
)
SELECT Country, Description, revenue
FROM ProductCountryRevenue
WHERE rn = 1
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 2. Highest revenue-generating customer within each country
-- =====================================================
-- Columns used: Country, CustomerID, Quantity, UnitPrice
-- Query:
WITH CustomerCountryRevenue AS (
    SELECT
        Country,
        CustomerID,
        ROUND(SUM(Quantity * UnitPrice), 2) AS revenue,
        ROW_NUMBER() OVER (
            PARTITION BY Country
            ORDER BY SUM(Quantity * UnitPrice) DESC
        ) AS rn
    FROM dbo.online_retail_clean
    WHERE CustomerID IS NOT NULL
      AND Quantity > 0
      AND UnitPrice > 0
    GROUP BY Country, CustomerID
)
SELECT Country, CustomerID, revenue
FROM CustomerCountryRevenue
WHERE rn = 1
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 3. Customers generating above-average revenue
-- =====================================================
-- Columns used: CustomerID, Quantity, UnitPrice
-- Query:
WITH CustomerRevenue AS (
    SELECT
        CustomerID,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE CustomerID IS NOT NULL
      AND Quantity > 0
      AND UnitPrice > 0
    GROUP BY CustomerID
)
SELECT
    CustomerID,
    ROUND(revenue, 2) AS revenue
FROM CustomerRevenue
WHERE revenue > (SELECT AVG(revenue) FROM CustomerRevenue)
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 4. Products generating above-average revenue
-- =====================================================
-- Columns used: Description, Quantity, UnitPrice
-- Query:
WITH ProductRevenue AS (
    SELECT
        Description,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE Quantity > 0
      AND UnitPrice > 0
      AND Description IS NOT NULL
    GROUP BY Description
)
SELECT
    Description,
    ROUND(revenue, 2) AS revenue
FROM ProductRevenue
WHERE revenue > (SELECT AVG(revenue) FROM ProductRevenue)
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 5. Revenue contribution percentage by country
-- =====================================================
-- Columns used: Country, Quantity, UnitPrice
-- Query:
SELECT
    Country,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue,
    ROUND(
        SUM(Quantity * UnitPrice) * 100.0 /
        SUM(SUM(Quantity * UnitPrice)) OVER (),
        2
    ) AS revenue_percentage
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0
GROUP BY Country
ORDER BY revenue_percentage DESC;
-- =====================================================

-- =====================================================
-- 6. Repeat customers purchasing across multiple months
-- =====================================================
-- Columns used: CustomerID, InvoiceDate, InvoiceNo
-- Query:
SELECT
    CustomerID,
    COUNT(DISTINCT FORMAT(InvoiceDate, 'yyyy-MM')) AS active_months,
    COUNT(DISTINCT InvoiceNo) AS total_orders
FROM dbo.online_retail_clean
WHERE CustomerID IS NOT NULL
  AND Quantity > 0
GROUP BY CustomerID
HAVING COUNT(DISTINCT FORMAT(InvoiceDate, 'yyyy-MM')) > 1
ORDER BY active_months DESC, total_orders DESC;
-- =====================================================

-- =====================================================
-- 7. Highest revenue-generating day of the week
-- =====================================================
-- Columns used: InvoiceDate, Quantity, UnitPrice
-- Query:
SELECT
    DATENAME(WEEKDAY, InvoiceDate) AS day_of_week,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0
GROUP BY DATENAME(WEEKDAY, InvoiceDate)
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 8. Fastest-growing revenue month
-- =====================================================
-- Columns used: InvoiceDate, Quantity, UnitPrice
-- Query:
WITH MonthlyRevenue AS (
    SELECT
        YEAR(InvoiceDate) AS sales_year,
        MONTH(InvoiceDate) AS sales_month,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE Quantity > 0
      AND UnitPrice > 0
    GROUP BY YEAR(InvoiceDate), MONTH(InvoiceDate)
),
Growth AS (
    SELECT
        sales_year,
        sales_month,
        revenue,
        LAG(revenue) OVER (ORDER BY sales_year, sales_month) AS previous_month_revenue
    FROM MonthlyRevenue
)
SELECT
    sales_year,
    sales_month,
    ROUND(revenue, 2) AS revenue,
    ROUND(previous_month_revenue, 2) AS previous_month_revenue,
    ROUND(
        (revenue - previous_month_revenue) * 100.0 /
        NULLIF(previous_month_revenue, 0),
        2
    ) AS growth_percentage
FROM Growth
WHERE previous_month_revenue IS NOT NULL
ORDER BY growth_percentage DESC;
-- =====================================================

-- =====================================================
-- 9. Customers contributing to the majority of business revenue
-- =====================================================
-- Columns used: CustomerID, Quantity, UnitPrice
-- Query:
WITH CustomerRevenue AS (
    SELECT
        CustomerID,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE CustomerID IS NOT NULL
      AND Quantity > 0
      AND UnitPrice > 0
    GROUP BY CustomerID
),
RevenueContribution AS (
    SELECT
        CustomerID,
        revenue,
        SUM(revenue) OVER (ORDER BY revenue DESC) AS running_revenue,
        SUM(revenue) OVER () AS total_revenue
    FROM CustomerRevenue
)
SELECT
    CustomerID,
    ROUND(revenue, 2) AS revenue,
    ROUND(running_revenue * 100.0 / total_revenue, 2) AS cumulative_revenue_percentage
FROM RevenueContribution
WHERE running_revenue <= total_revenue * 0.80
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 10. Financial impact of cancelled orders
-- =====================================================
-- Columns used: InvoiceNo, Quantity, UnitPrice
-- Query:
SELECT
    COUNT(DISTINCT InvoiceNo) AS cancelled_orders,
    ROUND(SUM(ABS(Quantity) * UnitPrice), 2) AS cancelled_revenue_impact
FROM dbo.online_retail_clean
WHERE Quantity < 0
  AND UnitPrice > 0;  
-- =====================================================

-- UNIVARIATE ANALYSIS
-- =====================================================

-- =====================================================
-- 1. Quantity sold distribution
-- =====================================================
-- Columns used: Quantity
-- Query:
SELECT
    CASE
        WHEN Quantity < 0 THEN 'Returns'
        WHEN Quantity BETWEEN 1 AND 10 THEN '1-10'
        WHEN Quantity BETWEEN 11 AND 50 THEN '11-50'
        WHEN Quantity BETWEEN 51 AND 100 THEN '51-100'
        ELSE '100+'
    END AS quantity_range,
    COUNT(*) AS transaction_count
FROM dbo.online_retail_clean
GROUP BY
    CASE
        WHEN Quantity < 0 THEN 'Returns'
        WHEN Quantity BETWEEN 1 AND 10 THEN '1-10'
        WHEN Quantity BETWEEN 11 AND 50 THEN '11-50'
        WHEN Quantity BETWEEN 51 AND 100 THEN '51-100'
        ELSE '100+'
    END
ORDER BY transaction_count DESC;
-- =====================================================

-- =====================================================
-- 2. Unit price distribution
-- =====================================================
-- Columns used: UnitPrice
-- Query:
SELECT
    CASE
        WHEN UnitPrice = 0 THEN 'Zero Price'
        WHEN UnitPrice BETWEEN 0.01 AND 1 THEN '£0.01-£1'
        WHEN UnitPrice BETWEEN 1.01 AND 5 THEN '£1.01-£5'
        WHEN UnitPrice BETWEEN 5.01 AND 20 THEN '£5.01-£20'
        ELSE '£20+'
    END AS price_range,
    COUNT(*) AS transaction_count
FROM dbo.online_retail_clean
GROUP BY
    CASE
        WHEN UnitPrice = 0 THEN 'Zero Price'
        WHEN UnitPrice BETWEEN 0.01 AND 1 THEN '£0.01-£1'
        WHEN UnitPrice BETWEEN 1.01 AND 5 THEN '£1.01-£5'
        WHEN UnitPrice BETWEEN 5.01 AND 20 THEN '£5.01-£20'
        ELSE '£20+'
    END
ORDER BY transaction_count DESC;
-- =====================================================

-- =====================================================
-- 3. Revenue distribution
-- =====================================================
-- Columns used: Quantity, UnitPrice
-- Query:
SELECT
    CASE
        WHEN Quantity * UnitPrice < 0 THEN 'Negative Revenue'
        WHEN Quantity * UnitPrice BETWEEN 0 AND 10 THEN '£0-£10'
        WHEN Quantity * UnitPrice BETWEEN 10.01 AND 50 THEN '£10.01-£50'
        WHEN Quantity * UnitPrice BETWEEN 50.01 AND 100 THEN '£50.01-£100'
        ELSE '£100+'
    END AS revenue_range,
    COUNT(*) AS transaction_count
FROM dbo.online_retail_clean
GROUP BY
    CASE
        WHEN Quantity * UnitPrice < 0 THEN 'Negative Revenue'
        WHEN Quantity * UnitPrice BETWEEN 0 AND 10 THEN '£0-£10'
        WHEN Quantity * UnitPrice BETWEEN 10.01 AND 50 THEN '£10.01-£50'
        WHEN Quantity * UnitPrice BETWEEN 50.01 AND 100 THEN '£50.01-£100'
        ELSE '£100+'
    END
ORDER BY transaction_count DESC;
-- =====================================================

-- =====================================================
-- 4. Country transaction distribution
-- =====================================================
-- Columns used: Country
-- Query:
SELECT
    Country,
    COUNT(*) AS transaction_count
FROM dbo.online_retail_clean
GROUP BY Country
ORDER BY transaction_count DESC;
-- =====================================================

-- =====================================================
-- 5. Monthly transaction distribution
-- =====================================================
-- Columns used: InvoiceDate
-- Query:
SELECT
    YEAR(InvoiceDate) AS sales_year,
    MONTH(InvoiceDate) AS sales_month,
    COUNT(*) AS transaction_count
FROM dbo.online_retail_clean
GROUP BY YEAR(InvoiceDate), MONTH(InvoiceDate)
ORDER BY sales_year, sales_month;
-- =====================================================

-- =====================================================
-- 6. Customer purchase frequency distribution
-- =====================================================
-- Columns used: CustomerID, InvoiceNo
-- Query:
SELECT
    CASE
        WHEN order_count = 1 THEN '1 Order'
        WHEN order_count BETWEEN 2 AND 5 THEN '2-5 Orders'
        WHEN order_count BETWEEN 6 AND 10 THEN '6-10 Orders'
        ELSE '10+ Orders'
    END AS customer_order_frequency,
    COUNT(*) AS customer_count
FROM (
    SELECT
        CustomerID,
        COUNT(DISTINCT InvoiceNo) AS order_count
    FROM dbo.online_retail_clean
    WHERE CustomerID IS NOT NULL
      AND Quantity > 0
    GROUP BY CustomerID
) c
GROUP BY
    CASE
        WHEN order_count = 1 THEN '1 Order'
        WHEN order_count BETWEEN 2 AND 5 THEN '2-5 Orders'
        WHEN order_count BETWEEN 6 AND 10 THEN '6-10 Orders'
        ELSE '10+ Orders'
    END
ORDER BY customer_count DESC;
-- =====================================================

-- =====================================================
-- 7. Product demand distribution
-- =====================================================
-- Columns used: Description, Quantity
-- Query:
SELECT
    CASE
        WHEN total_quantity BETWEEN 1 AND 100 THEN 'Low Demand'
        WHEN total_quantity BETWEEN 101 AND 1000 THEN 'Medium Demand'
        ELSE 'High Demand'
    END AS product_demand_segment,
    COUNT(*) AS product_count
FROM (
    SELECT
        Description,
        SUM(Quantity) AS total_quantity
    FROM dbo.online_retail_clean
    WHERE Quantity > 0
      AND Description IS NOT NULL
    GROUP BY Description
) p
GROUP BY
    CASE
        WHEN total_quantity BETWEEN 1 AND 100 THEN 'Low Demand'
        WHEN total_quantity BETWEEN 101 AND 1000 THEN 'Medium Demand'
        ELSE 'High Demand'
    END;
-- =====================================================

-- =====================================================
-- 8. Order size distribution
-- =====================================================
-- Columns used: InvoiceNo, Quantity
-- Query:
SELECT
    CASE
        WHEN order_quantity BETWEEN 1 AND 50 THEN 'Small Order'
        WHEN order_quantity BETWEEN 51 AND 200 THEN 'Medium Order'
        ELSE 'Large Order'
    END AS order_size_segment,
    COUNT(*) AS order_count
FROM (
    SELECT
        InvoiceNo,
        SUM(Quantity) AS order_quantity
    FROM dbo.online_retail_clean
    WHERE Quantity > 0
    GROUP BY InvoiceNo
) o
GROUP BY
    CASE
        WHEN order_quantity BETWEEN 1 AND 50 THEN 'Small Order'
        WHEN order_quantity BETWEEN 51 AND 200 THEN 'Medium Order'
        ELSE 'Large Order'
    END;
-- =====================================================

-- =====================================================
-- 9. Return transaction distribution
-- =====================================================
-- Columns used: Quantity
-- Query:
SELECT
    CASE
        WHEN Quantity < 0 THEN 'Return Transaction'
        ELSE 'Non-Return Transaction'
    END AS transaction_type,
    COUNT(*) AS transaction_count
FROM dbo.online_retail_clean
GROUP BY
    CASE
        WHEN Quantity < 0 THEN 'Return Transaction'
        ELSE 'Non-Return Transaction'
    END;
-- =====================================================

-- =====================================================
-- 10. Invoice distribution
-- =====================================================
-- Columns used: InvoiceNo
-- Query:
SELECT
    COUNT(DISTINCT InvoiceNo) AS total_invoices,
    COUNT(*) AS total_invoice_lines
FROM dbo.online_retail_clean;
-- =====================================================

-- BIVARIATE ANALYSIS
-- =====================================================

-- =====================================================
-- 1. Quantity sold and revenue relationship
-- =====================================================
-- Columns used: Quantity, UnitPrice
-- Query:
SELECT
    CASE
        WHEN Quantity BETWEEN 1 AND 10 THEN '1-10'
        WHEN Quantity BETWEEN 11 AND 50 THEN '11-50'
        WHEN Quantity BETWEEN 51 AND 100 THEN '51-100'
        ELSE '100+'
    END AS quantity_range,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0
GROUP BY
    CASE
        WHEN Quantity BETWEEN 1 AND 10 THEN '1-10'
        WHEN Quantity BETWEEN 11 AND 50 THEN '11-50'
        WHEN Quantity BETWEEN 51 AND 100 THEN '51-100'
        ELSE '100+'
    END
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 2. Product and revenue relationship
-- =====================================================
-- Columns used: Description, Quantity, UnitPrice
-- Query:
SELECT TOP 20
    Description,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0
  AND Description IS NOT NULL
GROUP BY Description
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 3. Country and revenue relationship
-- =====================================================
-- Columns used: Country, Quantity, UnitPrice
-- Query:
SELECT
    Country,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0
GROUP BY Country
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 4. Customer and revenue relationship
-- =====================================================
-- Columns used: CustomerID, Quantity, UnitPrice
-- Query:
SELECT TOP 20
    CustomerID,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue
FROM dbo.online_retail_clean
WHERE CustomerID IS NOT NULL
  AND Quantity > 0
  AND UnitPrice > 0
GROUP BY CustomerID
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 5. Month and revenue relationship
-- =====================================================
-- Columns used: InvoiceDate, Quantity, UnitPrice
-- Query:
SELECT
    YEAR(InvoiceDate) AS sales_year,
    MONTH(InvoiceDate) AS sales_month,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0
GROUP BY YEAR(InvoiceDate), MONTH(InvoiceDate)
ORDER BY sales_year, sales_month;
-- =====================================================

-- =====================================================
-- 6. Country and order volume relationship
-- =====================================================
-- Columns used: Country, InvoiceNo
-- Query:
SELECT
    Country,
    COUNT(DISTINCT InvoiceNo) AS total_orders
FROM dbo.online_retail_clean
WHERE Quantity > 0
GROUP BY Country
ORDER BY total_orders DESC;
-- =====================================================

-- =====================================================
-- 7. Product and quantity sold relationship
-- =====================================================
-- Columns used: Description, Quantity
-- Query:
SELECT TOP 20
    Description,
    SUM(Quantity) AS total_quantity_sold
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND Description IS NOT NULL
GROUP BY Description
ORDER BY total_quantity_sold DESC;
-- =====================================================

-- =====================================================
-- 8. Customer and order frequency relationship
-- =====================================================
-- Columns used: CustomerID, InvoiceNo
-- Query:
SELECT TOP 20
    CustomerID,
    COUNT(DISTINCT InvoiceNo) AS total_orders
FROM dbo.online_retail_clean
WHERE CustomerID IS NOT NULL
  AND Quantity > 0
GROUP BY CustomerID
ORDER BY total_orders DESC;
-- =====================================================

-- =====================================================
-- 9. Unit price and quantity sold relationship
-- =====================================================
-- Columns used: UnitPrice, Quantity
-- Query:
SELECT
    CASE
        WHEN UnitPrice BETWEEN 0.01 AND 1 THEN '£0.01-£1'
        WHEN UnitPrice BETWEEN 1.01 AND 5 THEN '£1.01-£5'
        WHEN UnitPrice BETWEEN 5.01 AND 20 THEN '£5.01-£20'
        ELSE '£20+'
    END AS price_range,
    SUM(Quantity) AS total_quantity_sold
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0
GROUP BY
    CASE
        WHEN UnitPrice BETWEEN 0.01 AND 1 THEN '£0.01-£1'
        WHEN UnitPrice BETWEEN 1.01 AND 5 THEN '£1.01-£5'
        WHEN UnitPrice BETWEEN 5.01 AND 20 THEN '£5.01-£20'
        ELSE '£20+'
    END
ORDER BY total_quantity_sold DESC;
-- =====================================================

-- =====================================================
-- 10. Returns and revenue relationship
-- =====================================================
-- Columns used: Quantity, UnitPrice
-- Query:
SELECT
    CASE
        WHEN Quantity < 0 THEN 'Returned'
        ELSE 'Completed Sale'
    END AS transaction_type,
    ROUND(SUM(Quantity * UnitPrice), 2) AS net_revenue,
    COUNT(*) AS transaction_count
FROM dbo.online_retail_clean
GROUP BY
    CASE
        WHEN Quantity < 0 THEN 'Returned'
        ELSE 'Completed Sale'
    END;
-- =====================================================

-- MULTIVARIATE ANALYSIS
-- =====================================================

-- =====================================================
-- 1. Country, product and revenue analysis
-- =====================================================
-- Columns used: Country, Description, Quantity, UnitPrice
-- Query:
SELECT TOP 50
    Country,
    Description,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0
  AND Description IS NOT NULL
GROUP BY Country, Description
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 2. Customer, product and revenue analysis
-- =====================================================
-- Columns used: CustomerID, Description, Quantity, UnitPrice
-- Query:
SELECT TOP 50
    CustomerID,
    Description,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue
FROM dbo.online_retail_clean
WHERE CustomerID IS NOT NULL
  AND Quantity > 0
  AND UnitPrice > 0
  AND Description IS NOT NULL
GROUP BY CustomerID, Description
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 3. Month, year and revenue analysis
-- =====================================================
-- Columns used: InvoiceDate, Quantity, UnitPrice
-- Query:
SELECT
    YEAR(InvoiceDate) AS sales_year,
    MONTH(InvoiceDate) AS sales_month,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue,
    COUNT(DISTINCT InvoiceNo) AS total_orders
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0
GROUP BY YEAR(InvoiceDate), MONTH(InvoiceDate)
ORDER BY sales_year, sales_month;
-- =====================================================

-- =====================================================
-- 4. Country, customer and order value analysis
-- =====================================================
-- Columns used: Country, CustomerID, InvoiceNo, Quantity, UnitPrice
-- Query:
SELECT TOP 50
    Country,
    CustomerID,
    InvoiceNo,
    ROUND(SUM(Quantity * UnitPrice), 2) AS order_value
FROM dbo.online_retail_clean
WHERE CustomerID IS NOT NULL
  AND Quantity > 0
  AND UnitPrice > 0
GROUP BY Country, CustomerID, InvoiceNo
ORDER BY order_value DESC;
-- =====================================================

-- =====================================================
-- 5. Product, quantity and revenue analysis
-- =====================================================
-- Columns used: Description, Quantity, UnitPrice
-- Query:
SELECT TOP 50
    Description,
    SUM(Quantity) AS total_quantity_sold,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0
  AND Description IS NOT NULL
GROUP BY Description
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 6. Country, product and quantity sold analysis
-- =====================================================
-- Columns used: Country, Description, Quantity
-- Query:
SELECT TOP 50
    Country,
    Description,
    SUM(Quantity) AS total_quantity_sold
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND Description IS NOT NULL
GROUP BY Country, Description
ORDER BY total_quantity_sold DESC;
-- =====================================================

-- =====================================================
-- 7. Customer, revenue and purchase frequency analysis
-- =====================================================
-- Columns used: CustomerID, InvoiceNo, Quantity, UnitPrice
-- Query:
SELECT TOP 50
    CustomerID,
    COUNT(DISTINCT InvoiceNo) AS order_frequency,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue
FROM dbo.online_retail_clean
WHERE CustomerID IS NOT NULL
  AND Quantity > 0
  AND UnitPrice > 0
GROUP BY CustomerID
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 8. Country, month and revenue analysis
-- =====================================================
-- Columns used: Country, InvoiceDate, Quantity, UnitPrice
-- Query:
SELECT
    Country,
    YEAR(InvoiceDate) AS sales_year,
    MONTH(InvoiceDate) AS sales_month,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0
GROUP BY Country, YEAR(InvoiceDate), MONTH(InvoiceDate)
ORDER BY sales_year, sales_month, revenue DESC;
-- =====================================================

-- =====================================================
-- 9. Customer, country and revenue analysis
-- =====================================================
-- Columns used: CustomerID, Country, Quantity, UnitPrice
-- Query:
SELECT TOP 50
    CustomerID,
    Country,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue
FROM dbo.online_retail_clean
WHERE CustomerID IS NOT NULL
  AND Quantity > 0
  AND UnitPrice > 0
GROUP BY CustomerID, Country
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 10. Product, country and return analysis
-- =====================================================
-- Columns used: Description, Country, Quantity, UnitPrice
-- Query:
SELECT TOP 50
    Description,
    Country,
    SUM(ABS(Quantity)) AS returned_quantity,
    ROUND(SUM(ABS(Quantity) * UnitPrice), 2) AS return_value
FROM dbo.online_retail_clean
WHERE Quantity < 0
  AND UnitPrice > 0
  AND Description IS NOT NULL
GROUP BY Description, Country
ORDER BY return_value DESC;
-- =====================================================

-- CTE PROBLEMS
-- =====================================================

-- =====================================================
-- 1. Top revenue product analysis
-- =====================================================
-- Columns used: Description, Quantity, UnitPrice
-- Query:
WITH ProductRevenue AS (
    SELECT
        Description,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE Quantity > 0
      AND UnitPrice > 0
      AND Description IS NOT NULL
    GROUP BY Description
)
SELECT TOP 10
    Description,
    ROUND(revenue, 2) AS revenue
FROM ProductRevenue
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 2. Top revenue customer analysis
-- =====================================================
-- Columns used: CustomerID, Quantity, UnitPrice
-- Query:
WITH CustomerRevenue AS (
    SELECT
        CustomerID,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE CustomerID IS NOT NULL
      AND Quantity > 0
      AND UnitPrice > 0
    GROUP BY CustomerID
)
SELECT TOP 10
    CustomerID,
    ROUND(revenue, 2) AS revenue
FROM CustomerRevenue
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 3. Monthly revenue analysis
-- =====================================================
-- Columns used: InvoiceDate, Quantity, UnitPrice
-- Query:
WITH MonthlyRevenue AS (
    SELECT
        YEAR(InvoiceDate) AS sales_year,
        MONTH(InvoiceDate) AS sales_month,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE Quantity > 0
      AND UnitPrice > 0
    GROUP BY YEAR(InvoiceDate), MONTH(InvoiceDate)
)
SELECT
    sales_year,
    sales_month,
    ROUND(revenue, 2) AS revenue
FROM MonthlyRevenue
ORDER BY sales_year, sales_month;
-- =====================================================

-- =====================================================
-- 4. Country revenue analysis
-- =====================================================
-- Columns used: Country, Quantity, UnitPrice
-- Query:
WITH CountryRevenue AS (
    SELECT
        Country,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE Quantity > 0
      AND UnitPrice > 0
    GROUP BY Country
)
SELECT
    Country,
    ROUND(revenue, 2) AS revenue
FROM CountryRevenue
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 5. Products generating above-average revenue
-- =====================================================
-- Columns used: Description, Quantity, UnitPrice
-- Query:
WITH ProductRevenue AS (
    SELECT
        Description,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE Quantity > 0
      AND UnitPrice > 0
      AND Description IS NOT NULL
    GROUP BY Description
),
AverageProductRevenue AS (
    SELECT AVG(revenue) AS avg_product_revenue
    FROM ProductRevenue
)
SELECT
    p.Description,
    ROUND(p.revenue, 2) AS revenue
FROM ProductRevenue p
CROSS JOIN AverageProductRevenue a
WHERE p.revenue > a.avg_product_revenue
ORDER BY p.revenue DESC;


-- 6. Customers spending above average revenue
-- Columns used: CustomerID, Quantity, UnitPrice
-- Query:
WITH CustomerRevenue AS (
    SELECT
        CustomerID,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE CustomerID IS NOT NULL
      AND Quantity > 0
      AND UnitPrice > 0
    GROUP BY CustomerID
),
AverageCustomerRevenue AS (
    SELECT AVG(revenue) AS avg_customer_revenue
    FROM CustomerRevenue
)
SELECT
    c.CustomerID,
    ROUND(c.revenue, 2) AS revenue
FROM CustomerRevenue c
CROSS JOIN AverageCustomerRevenue a
WHERE c.revenue > a.avg_customer_revenue
ORDER BY c.revenue DESC;
-- =====================================================

-- =====================================================
-- 7. Top order value by country
-- =====================================================
-- Columns used: Country, InvoiceNo, Quantity, UnitPrice
-- Query:
WITH OrderValue AS (
    SELECT
        Country,
        InvoiceNo,
        SUM(Quantity * UnitPrice) AS order_value
    FROM dbo.online_retail_clean
    WHERE Quantity > 0
      AND UnitPrice > 0
    GROUP BY Country, InvoiceNo
),
RankedOrders AS (
    SELECT
        Country,
        InvoiceNo,
        order_value,
        ROW_NUMBER() OVER (
            PARTITION BY Country
            ORDER BY order_value DESC
        ) AS rn
    FROM OrderValue
)
SELECT
    Country,
    InvoiceNo,
    ROUND(order_value, 2) AS order_value
FROM RankedOrders
WHERE rn = 1
ORDER BY order_value DESC;
-- =====================================================

-- =====================================================
-- 8. Cumulative monthly revenue analysis
-- =====================================================
-- Columns used: InvoiceDate, Quantity, UnitPrice
-- Query:
WITH MonthlyRevenue AS (
    SELECT
        YEAR(InvoiceDate) AS sales_year,
        MONTH(InvoiceDate) AS sales_month,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE Quantity > 0
      AND UnitPrice > 0
    GROUP BY YEAR(InvoiceDate), MONTH(InvoiceDate)
)
SELECT
    sales_year,
    sales_month,
    ROUND(revenue, 2) AS monthly_revenue,
    ROUND(
        SUM(revenue) OVER (
            ORDER BY sales_year, sales_month
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ),
        2
    ) AS cumulative_revenue
FROM MonthlyRevenue
ORDER BY sales_year, sales_month;
-- =====================================================

-- =====================================================
-- 9. Product revenue contribution analysis
-- =====================================================
-- Columns used: Description, Quantity, UnitPrice
-- Query:
WITH ProductRevenue AS (
    SELECT
        Description,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE Quantity > 0
      AND UnitPrice > 0
      AND Description IS NOT NULL
    GROUP BY Description
)
SELECT
    Description,
    ROUND(revenue, 2) AS revenue,
    ROUND(
        revenue * 100.0 / SUM(revenue) OVER (),
        2
    ) AS revenue_contribution_percentage
FROM ProductRevenue
ORDER BY revenue_contribution_percentage DESC;
-- =====================================================

-- =====================================================
-- 10. High-value customer identification
-- =====================================================
-- Columns used: CustomerID, Quantity, UnitPrice
-- Query:
WITH CustomerRevenue AS (
    SELECT
        CustomerID,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE CustomerID IS NOT NULL
      AND Quantity > 0
      AND UnitPrice > 0
    GROUP BY CustomerID
)
SELECT
    CustomerID,
    ROUND(revenue, 2) AS revenue,
    CASE
        WHEN revenue >= 10000 THEN 'High Value Customer'
        WHEN revenue >= 5000 THEN 'Medium Value Customer'
        ELSE 'Low Value Customer'
    END AS customer_value_segment
FROM CustomerRevenue
ORDER BY revenue DESC;
-- =====================================================

-- WINDOW FUNCTION PROBLEMS
-- =====================================================

-- =====================================================
-- 1. Product revenue ranking
-- =====================================================
-- Columns used: Description, Quantity, UnitPrice
-- Query:
SELECT
    Description,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue,
    RANK() OVER (
        ORDER BY SUM(Quantity * UnitPrice) DESC
    ) AS revenue_rank
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0
  AND Description IS NOT NULL
GROUP BY Description
ORDER BY revenue_rank;
-- =====================================================

-- =====================================================
-- 2. Customer revenue ranking
-- =====================================================
-- Columns used: CustomerID, Quantity, UnitPrice
-- Query:
SELECT
    CustomerID,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue,
    RANK() OVER (
        ORDER BY SUM(Quantity * UnitPrice) DESC
    ) AS revenue_rank
FROM dbo.online_retail_clean
WHERE CustomerID IS NOT NULL
  AND Quantity > 0
  AND UnitPrice > 0
GROUP BY CustomerID
ORDER BY revenue_rank;
-- =====================================================

-- =====================================================
-- 3. Country revenue ranking
-- =====================================================
-- Columns used: Country, Quantity, UnitPrice
-- Query:
SELECT
    Country,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue,
    RANK() OVER (
        ORDER BY SUM(Quantity * UnitPrice) DESC
    ) AS revenue_rank
FROM dbo.online_retail_clean
WHERE Quantity > 0
  AND UnitPrice > 0
GROUP BY Country
ORDER BY revenue_rank;
-- =====================================================

-- =====================================================
-- 4. Top product within each country
-- =====================================================
-- Columns used: Country, Description, Quantity, UnitPrice
-- Query:
WITH ProductCountryRevenue AS (
    SELECT
        Country,
        Description,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE Quantity > 0
      AND UnitPrice > 0
      AND Description IS NOT NULL
    GROUP BY Country, Description
),
RankedProducts AS (
    SELECT
        Country,
        Description,
        revenue,
        ROW_NUMBER() OVER (
            PARTITION BY Country
            ORDER BY revenue DESC
        ) AS rn
    FROM ProductCountryRevenue
)
SELECT
    Country,
    Description,
    ROUND(revenue, 2) AS revenue
FROM RankedProducts
WHERE rn = 1
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 5. Top customer within each country
-- =====================================================
-- Columns used: Country, CustomerID, Quantity, UnitPrice
-- Query:
WITH CustomerCountryRevenue AS (
    SELECT
        Country,
        CustomerID,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE CustomerID IS NOT NULL
      AND Quantity > 0
      AND UnitPrice > 0
    GROUP BY Country, CustomerID
),
RankedCustomers AS (
    SELECT
        Country,
        CustomerID,
        revenue,
        ROW_NUMBER() OVER (
            PARTITION BY Country
            ORDER BY revenue DESC
        ) AS rn
    FROM CustomerCountryRevenue
)
SELECT
    Country,
    CustomerID,
    ROUND(revenue, 2) AS revenue
FROM RankedCustomers
WHERE rn = 1
ORDER BY revenue DESC;
-- =====================================================

-- =====================================================
-- 6. Running monthly revenue calculation
-- =====================================================
-- Columns used: InvoiceDate, Quantity, UnitPrice
-- Query:
WITH MonthlyRevenue AS (
    SELECT
        YEAR(InvoiceDate) AS sales_year,
        MONTH(InvoiceDate) AS sales_month,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE Quantity > 0
      AND UnitPrice > 0
    GROUP BY YEAR(InvoiceDate), MONTH(InvoiceDate)
)
SELECT
    sales_year,
    sales_month,
    ROUND(revenue, 2) AS monthly_revenue,
    ROUND(
        SUM(revenue) OVER (
            ORDER BY sales_year, sales_month
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ),
        2
    ) AS running_revenue
FROM MonthlyRevenue
ORDER BY sales_year, sales_month;
-- =====================================================

-- =====================================================
-- 7. Running customer revenue calculation
-- =====================================================
-- Columns used: CustomerID, Quantity, UnitPrice
-- Query:
WITH CustomerRevenue AS (
    SELECT
        CustomerID,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE CustomerID IS NOT NULL
      AND Quantity > 0
      AND UnitPrice > 0
    GROUP BY CustomerID
)
SELECT
    CustomerID,
    ROUND(revenue, 2) AS customer_revenue,
    ROUND(
        SUM(revenue) OVER (
            ORDER BY revenue DESC
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ),
        2
    ) AS running_customer_revenue
FROM CustomerRevenue
ORDER BY customer_revenue DESC;
-- =====================================================

-- =====================================================
-- 8. Month-over-month revenue comparison
-- =====================================================
-- Columns used: InvoiceDate, Quantity, UnitPrice
-- Query:
WITH MonthlyRevenue AS (
    SELECT
        YEAR(InvoiceDate) AS sales_year,
        MONTH(InvoiceDate) AS sales_month,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE Quantity > 0
      AND UnitPrice > 0
    GROUP BY YEAR(InvoiceDate), MONTH(InvoiceDate)
)
SELECT
    sales_year,
    sales_month,
    ROUND(revenue, 2) AS revenue,
    ROUND(
        LAG(revenue) OVER (ORDER BY sales_year, sales_month),
        2
    ) AS previous_month_revenue
FROM MonthlyRevenue
ORDER BY sales_year, sales_month;
-- =====================================================

-- =====================================================
-- 9. Revenue growth percentage analysis
-- =====================================================
-- Columns used: InvoiceDate, Quantity, UnitPrice
-- Query:
WITH MonthlyRevenue AS (
    SELECT
        YEAR(InvoiceDate) AS sales_year,
        MONTH(InvoiceDate) AS sales_month,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE Quantity > 0
      AND UnitPrice > 0
    GROUP BY YEAR(InvoiceDate), MONTH(InvoiceDate)
),
RevenueGrowth AS (
    SELECT
        sales_year,
        sales_month,
        revenue,
        LAG(revenue) OVER (ORDER BY sales_year, sales_month) AS previous_month_revenue
    FROM MonthlyRevenue
)
SELECT
    sales_year,
    sales_month,
    ROUND(revenue, 2) AS revenue,
    ROUND(previous_month_revenue, 2) AS previous_month_revenue,
    ROUND(
        (revenue - previous_month_revenue) * 100.0 /
        NULLIF(previous_month_revenue, 0),
        2
    ) AS revenue_growth_percentage
FROM RevenueGrowth
WHERE previous_month_revenue IS NOT NULL
ORDER BY sales_year, sales_month;
-- =====================================================

-- =====================================================
-- 10. Customer revenue quartile segmentation
-- =====================================================
-- Columns used: CustomerID, Quantity, UnitPrice
-- Query:
WITH CustomerRevenue AS (
    SELECT
        CustomerID,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE CustomerID IS NOT NULL
      AND Quantity > 0
      AND UnitPrice > 0
    GROUP BY CustomerID
)
SELECT
    CustomerID,
    ROUND(revenue, 2) AS revenue,
    NTILE(4) OVER (ORDER BY revenue DESC) AS revenue_quartile
FROM CustomerRevenue
ORDER BY revenue DESC;
-- =====================================================


-- CUSTOMER VALUE ANALYSIS (RFM)
-- =====================================================

-- =====================================================
-- 1. Customer recency analysis
-- =====================================================
-- Columns used: CustomerID, InvoiceDate
-- Query:
SELECT
    CustomerID,
    DATEDIFF(
        DAY,
        MAX(InvoiceDate),
        (SELECT MAX(InvoiceDate) FROM dbo.online_retail_clean)
    ) AS recency_days
FROM dbo.online_retail_clean
WHERE CustomerID IS NOT NULL
  AND Quantity > 0
GROUP BY CustomerID
ORDER BY recency_days ASC;
-- =====================================================

-- =====================================================
-- 2. Customer frequency analysis
-- =====================================================
-- Columns used: CustomerID, InvoiceNo
-- Query:
SELECT
    CustomerID,
    COUNT(DISTINCT InvoiceNo) AS frequency
FROM dbo.online_retail_clean
WHERE CustomerID IS NOT NULL
  AND Quantity > 0
GROUP BY CustomerID
ORDER BY frequency DESC;
-- =====================================================

-- =====================================================
-- 3. Customer monetary value analysis
-- =====================================================
-- Columns used: CustomerID, Quantity, UnitPrice
-- Query:
SELECT
    CustomerID,
    ROUND(SUM(Quantity * UnitPrice), 2) AS monetary_value
FROM dbo.online_retail_clean
WHERE CustomerID IS NOT NULL
  AND Quantity > 0
  AND UnitPrice > 0
GROUP BY CustomerID
ORDER BY monetary_value DESC;


-- 4. Customer RFM score generation
-- Columns used: CustomerID, InvoiceDate, InvoiceNo, Quantity, UnitPrice
-- Query:
WITH RFM AS (
    SELECT
        CustomerID,
        DATEDIFF(
            DAY,
            MAX(InvoiceDate),
            (SELECT MAX(InvoiceDate) FROM dbo.online_retail_clean)
        ) AS recency,
        COUNT(DISTINCT InvoiceNo) AS frequency,
        SUM(Quantity * UnitPrice) AS monetary
    FROM dbo.online_retail_clean
    WHERE CustomerID IS NOT NULL
      AND Quantity > 0
      AND UnitPrice > 0
    GROUP BY CustomerID
),
RFMScore AS (
    SELECT
        CustomerID,
        recency,
        frequency,
        monetary,
        NTILE(5) OVER (ORDER BY recency DESC) AS recency_score,
        NTILE(5) OVER (ORDER BY frequency ASC) AS frequency_score,
        NTILE(5) OVER (ORDER BY monetary ASC) AS monetary_score
    FROM RFM
)
SELECT
    CustomerID,
    recency,
    frequency,
    ROUND(monetary, 2) AS monetary,
    recency_score,
    frequency_score,
    monetary_score,
    recency_score + frequency_score + monetary_score AS rfm_total_score
FROM RFMScore
ORDER BY rfm_total_score DESC;
-- =====================================================

-- =====================================================
-- 5. VIP customer identification
-- =====================================================
-- Columns used: CustomerID, InvoiceDate, InvoiceNo, Quantity, UnitPrice
-- Query:
WITH RFM AS (
    SELECT
        CustomerID,
        DATEDIFF(
            DAY,
            MAX(InvoiceDate),
            (SELECT MAX(InvoiceDate) FROM dbo.online_retail_clean)
        ) AS recency,
        COUNT(DISTINCT InvoiceNo) AS frequency,
        SUM(Quantity * UnitPrice) AS monetary
    FROM dbo.online_retail_clean
    WHERE CustomerID IS NOT NULL
      AND Quantity > 0
      AND UnitPrice > 0
    GROUP BY CustomerID
)
SELECT
    CustomerID,
    recency,
    frequency,
    ROUND(monetary, 2) AS monetary
FROM RFM
WHERE recency <= 30
  AND frequency >= 10
  AND monetary >= 10000
ORDER BY monetary DESC;
-- =====================================================

-- =====================================================
-- 6. Loyal customer identification
-- =====================================================
-- Columns used: CustomerID, InvoiceNo, Quantity, UnitPrice
-- Query:
SELECT
    CustomerID,
    COUNT(DISTINCT InvoiceNo) AS frequency,
    ROUND(SUM(Quantity * UnitPrice), 2) AS monetary
FROM dbo.online_retail_clean
WHERE CustomerID IS NOT NULL
  AND Quantity > 0
  AND UnitPrice > 0
GROUP BY CustomerID
HAVING COUNT(DISTINCT InvoiceNo) >= 10
ORDER BY frequency DESC;
-- =====================================================

-- =====================================================
-- 7. High-value customer identification
-- =====================================================
-- Columns used: CustomerID, Quantity, UnitPrice
-- Query:
SELECT
    CustomerID,
    ROUND(SUM(Quantity * UnitPrice), 2) AS monetary
FROM dbo.online_retail_clean
WHERE CustomerID IS NOT NULL
  AND Quantity > 0
  AND UnitPrice > 0
GROUP BY CustomerID
HAVING SUM(Quantity * UnitPrice) >= 10000
ORDER BY monetary DESC;
-- =====================================================

-- =====================================================
-- 8. Dormant customer identification
-- =====================================================
-- Columns used: CustomerID, InvoiceDate
-- Query:
SELECT
    CustomerID,
    MAX(InvoiceDate) AS last_purchase_date,
    DATEDIFF(
        DAY,
        MAX(InvoiceDate),
        (SELECT MAX(InvoiceDate) FROM dbo.online_retail_clean)
    ) AS days_since_last_purchase
FROM dbo.online_retail_clean
WHERE CustomerID IS NOT NULL
  AND Quantity > 0
GROUP BY CustomerID
HAVING DATEDIFF(
        DAY,
        MAX(InvoiceDate),
        (SELECT MAX(InvoiceDate) FROM dbo.online_retail_clean)
    ) > 180
ORDER BY days_since_last_purchase DESC;
-- =====================================================

-- =====================================================
-- 9. Revenue contribution by customer segment
-- =====================================================
-- Columns used: CustomerID, Quantity, UnitPrice
-- Query:
WITH CustomerRevenue AS (
    SELECT
        CustomerID,
        SUM(Quantity * UnitPrice) AS monetary
    FROM dbo.online_retail_clean
    WHERE CustomerID IS NOT NULL
      AND Quantity > 0
      AND UnitPrice > 0
    GROUP BY CustomerID
),
Segments AS (
    SELECT
        CustomerID,
        monetary,
        CASE
            WHEN monetary >= 10000 THEN 'High Value'
            WHEN monetary >= 3000 THEN 'Medium Value'
            ELSE 'Low Value'
        END AS customer_segment
    FROM CustomerRevenue
)
SELECT
    customer_segment,
    COUNT(*) AS customer_count,
    ROUND(SUM(monetary), 2) AS segment_revenue,
    ROUND(SUM(monetary) * 100.0 / SUM(SUM(monetary)) OVER (), 2) AS revenue_percentage
FROM Segments
GROUP BY customer_segment
ORDER BY segment_revenue DESC;
-- =====================================================

-- =====================================================
-- 10. Identification of customers driving the majority of business revenue
-- =====================================================
-- Columns used: CustomerID, Quantity, UnitPrice
-- Query:
WITH CustomerRevenue AS (
    SELECT
        CustomerID,
        SUM(Quantity * UnitPrice) AS revenue
    FROM dbo.online_retail_clean
    WHERE CustomerID IS NOT NULL
      AND Quantity > 0
      AND UnitPrice > 0
    GROUP BY CustomerID
),
RevenueContribution AS (
    SELECT
        CustomerID,
        revenue,
        SUM(revenue) OVER (ORDER BY revenue DESC) AS cumulative_revenue,
        SUM(revenue) OVER () AS total_revenue
    FROM CustomerRevenue
)
SELECT
    CustomerID,
    ROUND(revenue, 2) AS revenue,
    ROUND(cumulative_revenue * 100.0 / total_revenue, 2) AS cumulative_revenue_percentage
FROM RevenueContribution
WHERE cumulative_revenue <= total_revenue * 0.80
ORDER BY revenue DESC;
-- =====================================================


/*
-- FINDINGS
-- ====================================

-- 1. The business generated £10.67 million in revenue from 19,960 completed orders.
-- ======================================================
-- Total Revenue: £10,666,684.49
-- Total Orders: 19,960
-- Total Customers: 4,338
-- Total Quantity Sold: 5,588,376
-- Average Order Value: £534.40

-- This indicates a high-volume online retail business with strong transaction activity.


-- 2. The United Kingdom dominates business revenue.
-- =======================================================
-- Top Revenue Countries:

Country	              Revenue	          Revenue %
United Kingdom   	£9,025,222.03	       84.61%
Netherlands	        £285,446.34         	2.68%
EIRE	            £283,453.96	            2.66%
Germany         	£228,867.14	            2.15%
France          	£209,715.11	            1.97%

-- The United Kingdom alone contributes 84.61% of total revenue, showing a heavy dependence on the domestic market.


-- 3. Revenue is concentrated among a small number of products.
-- ========================================================
-- Top Revenue Products:

Product	                                  Revenue
DOTCOM POSTAGE	                        £206,248.77
REGENCY CAKESTAND 3 TIER	            £174,484.74
PAPER CRAFT , LITTLE BIRDIE         	£168,469.59
WHITE HANGING HEART T-LIGHT HOLDER  	£106,292.77
PARTY BUNTING	                        £99,504.33

-- These products act as major revenue drivers for the business.

-- 4. A small group of customers generates substantial revenue.
-- ===================================================
-- Top Revenue Customers:

Customer ID	Revenue
14646	£280,206.02
18102	£259,657.30
17450	£194,550.79
16446	£168,472.49
14911	£143,825.06

-- Customer 14646 generated the highest revenue at £280,206.02.

-- 5. Revenue shows strong seasonal fluctuations.
-- ===================================================
-- Monthly Revenue Highlights:

Period	Revenue
Dec-2010	£823,746.14
Sep-2011	£1,058,590.17
Oct-2011	£1,154,979.29
Nov-2011	£1,509,496.32

-- November 2011 recorded the highest revenue of £1.51 million, indicating strong seasonal demand during the year-end shopping period.

-- 6. Returns create significant revenue loss.
-- ====================================================
-- Return Orders: 3,836
Revenue Impact of Returns: £896,812.48

Returned transactions represent a substantial financial impact on the business.

-- 7. Customer data quality issues exist.
-- =====================================================
-- Total Rows: 541,909
Missing Customer Records: 135,080
Missing Customer Percentage: 24.93%

Nearly one-quarter of transactions cannot be linked to a customer, limiting customer-level analysis accuracy.

-- 8. High-value customers generate the largest revenue contribution.
-- =======================================================
-- Customer Segment Revenue Contribution

Segment  	    Customers	    Revenue	       Revenue %
High Value	      104	     £3,653,544.46	    41.00%
Low Value	     3,782	     £3,037,017.04	    34.08%
Medium Value      452	     £2,220,846.35	    24.92%

-- Only 104 high-value customers generate 41% of total customer revenue, demonstrating a strong concentration of revenue among premium customers.

-- BUSINESS INSIGHTS:
-- =====================================
-- The business relies heavily on the United Kingdom market, creating potential geographic concentration risk.

-- A small number of products contribute disproportionately to overall revenue.

-- High-value customers are critical to business performance and should be prioritized.

-- Revenue peaks significantly during the final quarter of the year, indicating seasonal purchasing behavior.

-- Returns and cancellations represent nearly £900K in lost revenue and require operational attention.

-- Missing customer information affects customer analytics and segmentation quality.

-- RECOMMENDATIONS:
-- ====================================

-- Expand sales efforts in high-performing international markets such as the Netherlands, EIRE, Germany, and France to reduce dependence on the United Kingdom.

-- Increase inventory availability and marketing support for top-performing products including DOTCOM POSTAGE, REGENCY CAKESTAND 3 TIER, and PAPER CRAFT, LITTLE BIRDIE.

-- Develop loyalty and retention programs targeting high-value customers, who generate 41% of customer revenue.

-- Prepare inventory and operational capacity ahead of peak seasonal months, particularly September through November.

-- Investigate return-heavy products and operational processes to reduce the £896,812.48 revenue loss from returned transactions.

-- Improve customer identification and data collection processes to reduce the 24.93% missing customer rate.

-- CONCLUSION:

This analysis identified the primary drivers of revenue within the UK Online Retail business. 
Revenue is highly concentrated in the United Kingdom market, a limited number of products, and 
a small segment of high-value customers. Strong seasonal sales patterns were observed, with
November 2011 delivering the highest monthly revenue. While the business demonstrates strong revenue 
performance, opportunities exist to improve international growth, customer retention, product strategy,
data quality, and return management. These initiatives can support sustainable revenue growth 
and long-term business performance.

*/